modLoader = "javafml"
loaderVersion = "[43,)"
issueTrackerURL = "https://github.com/dragon-forge/ImprovableSkills/issues"
license = "All rights reserved"
[[mods]]
modId = "improvableskills"
version = "${file.jarVersion}"
displayName = "ImprovableSkills"
updateJSONURL = "https://api.modrinth.com/updates/9fT7HUaI/forge_updates.json"
displayURL = "https://modrinth.com/mod/9fT7HUaI"
logoFile = "icon.png"
authors = "Zeitheron"
description = '''
Boost player's abilities as well as granting useful abilities using single book and your XP. (And more)
'''
[[dependencies.improvableskills]]
modId = "forge"
mandatory = true
versionRange = "[43.2,)"
ordering = "NONE" # NONE/BEFORE/AFTER
side = "BOTH"
[[dependencies.improvableskills]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,1.20)"
ordering = "NONE"
side = "BOTH"
[[dependencies.improvableskills]]
modId = "hammerlib"
mandatory = true
versionRange = "[19.3.76,)"
ordering = "NONE"
side = "BOTH"
